
[server]
headless = true

[theme]

# From Bannanatree tutorial
# Primary accent color for interactive elements
primaryColor = "#eca8a8"

# Background color for the main content area.
backgroundColor = "#fff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#b5e1ff"

# Color used for almost all text.
textColor = "#000"