# Your Credentials your responsibility.

# Everything in this section will be available as an environment variable
database = "YouTube.db"

api_key = 'YouTube_API_key'
database_uri = "mysql+pymysql://<user>:<password>@<host>:<port>/<dbname>"
mongo_uri = "mongodb://username:Password@mongodb.local:27017/?authSource=admin"
  
[default_settings]
default_channel = ['TheRegent','theregent3397', 'SpaceRex','matthew_berman']
